# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a69c1f049e355ee95523c18d64cea06f2d7cfb41b5c625c0e00840f67df84b087903dd1f34d1e95058d2733ed7306b24668fa22eba46c6da025dbef58557dc

test:
  secret_key_base: 6b9ea8c97f7437728a3769e94385afd65e91f7c5887ace5e6791a436e39a4d3f51b5c4852c49b49b2354adc08969ded49b0e1b8355f388ab5649da8b8848b10c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
